### ISSUE TITLE
gym.error.NameNotFound: Environment PongNoFrameskip doesn't exist. 

### ISSUE THREAD

**Issue by histmeisah** [takuseno/d4rl-atari#15]
i try to use this repo ,and get wrong with following things

Traceback (most recent call last):
  File "D:\pythoncode\test01\test.py", line 4, in <module>
    env = gym.make('pong-mixed-v4') # -v{0, 1, 2, 3, 4} for datasets with the other random seeds
  File "D:\ide\conda\envs\testenv\lib\site-packages\gym\envs\registration.py", line 640, in make
    env = env_creator(**_kwargs)
  File "D:\ide\conda\envs\testenv\lib\site-packages\d4rl_atari\envs.py", line 59, in __init__
    AtariEnv.__init__(self, game=game, **kwargs)
  File "D:\ide\conda\envs\testenv\lib\site-packages\d4rl_atari\envs.py", line 27, in __init__
    env = AtariPreprocessing(gym.make(env_id),
  File "D:\ide\conda\envs\testenv\lib\site-packages\gym\envs\registration.py", line 569, in make
    _check_version_exists(ns, name, version)
  File "D:\ide\conda\envs\testenv\lib\site-packages\gym\envs\registration.py", line 219, in _check_version_exists
    _check_name_exists(ns, name)
  File "D:\ide\conda\envs\testenv\lib\site-packages\gym\envs\registration.py", line 198, in _check_name_exists
    f"Environment {name} doesn't exist{namespace_msg}. {suggestion_msg}"
gym.error.NameNotFound: Environment BreakoutNoFrameskip doesn't exist. 

Process finished with exit code 1

my python version is python==3.7 and here is my package:

Package                Version
---------------------- ---------
aiohttp                3.8.4
aiosignal              1.3.1
argcomplete            3.0.5
async-timeout          4.0.2
asynctest              0.13.0
atari-py               0.2.6
attrs                  22.2.0
boto                   2.49.0
cachetools             5.3.0
certifi                2022.12.7
cffi                   1.15.1
charset-normalizer     3.1.0
cloudpickle            2.2.1
crcmod                 1.7
cryptography           40.0.2
d4rl-atari             0.1
fasteners              0.18
frozenlist             1.3.3
gcs-oauth2-boto-plugin 3.0
google-apitools        0.5.32
google-auth            2.17.3
google-reauth          0.1.1
gsutil                 5.23
gym                    0.26.2
gym-notices            0.0.8
httplib2               0.20.4
idna                   3.4
importlib-metadata     5.2.0
monotonic              1.6
multidict              6.0.4
numpy                  1.21.6
oauth2client           4.1.3
opencv-python          4.7.0.72
pip                    22.3.1
pyasn1                 0.4.8
pyasn1-modules         0.2.8
pycparser              2.21
pyOpenSSL              23.1.1
pyparsing              3.0.9
pyu2f                  0.1.5
requests               2.28.2
retry-decorator        1.1.1
rsa                    4.7.2
setuptools             65.6.3
six                    1.16.0
typing_extensions      4.5.0
urllib3                1.26.15
wheel                  0.38.4
wincertstore           0.2
yarl                   1.8.2
zipp                   3.15.0
so i want to seak someone`s help.

**Comment by zxq-0058** [comment]
You can check the d4rl_atari/__init__.py which register the gym envs carefully, only the following gym envs are supported : [
        'adventure', 'air-raid', 'alien', 'amidar', 'assault', 'asterix',
        'asteroids', 'atlantis', 'bank-heist', 'battle-zone', 'beam-rider',
        'berzerk', 'bowling', 'boxing', 'breakout', 'carnival', 'centipede',
        'chopper-command', 'crazy-climber', 'defender', 'demon-attack',
        'double-dunk', 'elevator-action', 'enduro', 'fishing-derby', 'freeway',
        'frostbite', 'gopher', 'gravitar', 'hero', 'ice-hockey', 'jamesbond',
        'journey-escape', 'kangaroo', 'krull', 'kung-fu-master',
        'montezuma-revenge', 'ms-pacman', 'name-this-game', 'phoenix',
        'pitfall', 'pong', 'pooyan', 'private-eye', 'qbert', 'riverraid',
        'road-runner', 'robotank', 'seaquest', 'skiing', 'solaris',
        'space-invaders', 'star-gunner', 'tennis', 'time-pilot', 'tutankham',
        'up-n-down', 'venture', 'video-pinball', 'wizard-of-wor',
        'yars-revenge', 'zaxxon'
]:

**Comment by takuseno** [comment]
@zxq-0058 Hi, thanks for the issue. Can you try this?
```
$ pip install gym[atari,accept-rom-license]
```
