### ISSUE TITLE
some games not available?

### ISSUE THREAD

**Issue by weiguowilliam** [takuseno/d4rl-atari#5]
How can we find the names of all available datasets?

It looks like some games are not available:

```
d = gym.make('beamrider-mixed-v0')
```

The output is 

```
Traceback (most recent call last):
  File "/home/xx/anaconda3/envs/pomdp/lib/python3.6/site-packages/gym/envs/registration.py", line 132, in spec
    return self.env_specs[id]
KeyError: 'beamrider-mixed-v0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xx/anaconda3/envs/pomdp/lib/python3.6/site-packages/gym/envs/registration.py", line 156, in make
    return registry.make(id, **kwargs)
  File "/home/xx/anaconda3/envs/pomdp/lib/python3.6/site-packages/gym/envs/registration.py", line 100, in make
    spec = self.spec(path)
  File "/home/xx/anaconda3/envs/pomdp/lib/python3.6/site-packages/gym/envs/registration.py", line 142, in spec
    raise error.UnregisteredEnv('No registered env with id: {}'.format(id))
gym.error.UnregisteredEnv: No registered env with id: beamrider-mixed-v0

```

**Comment by takuseno** [comment]
@weiguowilliam Hello, sorry for the inconvenience. You can check the actual list here.
https://github.com/takuseno/d4rl-atari/blob/master/d4rl_atari/__init__.py
For example, BeamRider is `beam-rider`.

**Comment by weiguowilliam** [comment]
Thanks!
